<?php

include('functions.php');


error_reporting(E_ERROR | E_WARNING);

echo "<!DOCTYPE html>\n";
echo "<html class=' pp' lang='en'>\n";
echo "<head>\n";
echo "    <meta charset='utf-8'>\n";
echo "    <meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>\n";
echo "    <title>ProductPlan</title>\n";
echo "    <link rel=\"stylesheet\" media=\"all\" href=\"https://assets0.productplan.com/assets/application-0fbdc17e3f9f3ce8c309a48e9d64b9f9e07ea1b67ed588adcf5557d1e5a8fdb3.css\" />\n";
echo "    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"https://assets0.productplan.com/assets/favicon-ad9ab65e552a23afddc9a34a4fddb448f79362ab05cef1475c0b794327ba7377.ico\" />\n";
echo "\n";
echo "</head>\n";
echo "\n";
echo "<body data-action='edit' data-controller='registrationsController'>\n";
echo "    <!-- Google Tag Manager -->\n";
echo "    <noscript>\n";
echo "        <iframe src=\"//www.googletagmanager.com/ns.html?id=GTM-56MDRJ\" height=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe>\n";
echo "    </noscript>\n";
echo "    \n";
echo "    <!-- End Google Tag Manager -->\n";
echo "\n";
echo "    <nav class='navbar navbar-fixed-top navbar-default'>\n";
echo "        <div class='container-fluid'>\n";
echo "            <div class='navbar-header company-name'>\n";
echo "                <a class='navbar-brand' href='/' id='brand'>COPB</a>\n";
echo "            </div>\n";
echo "            <ul class='nav navbar-nav navbar-right user_menu'>\n";
echo "                <li><a id=\"roadmaps_header_link\" title=\"Create or view other roadmaps\" href=\"https://app.productplan.com/roadmaps\">Roadmaps</a>\n";
echo "                </li>\n";
echo "                <li class='notifications'></li>\n";
echo "                <li class='dropdown'>\n";
echo "                    <a class='dropdown-toggle pull-right' data-toggle='dropdown' href='#' id='user_menu'>\n";
echo "rencherga@ldschurch.org\n";
echo "<i class='fa fa-caret-down'></i>\n";
echo "<ul class='dropdown-menu'>\n";
echo "<li><a id=\"your_settings\" href=\"/user_settings/profile\">Your Settings</a>\n";
echo "                </li>\n";
echo "                <li>\n";
echo "                    <a id=\"billing\" href=\"/manage_subscription/overview\">Account Settings</a>\n";
echo "                </li>\n";
echo "                <li><a id=\"integrations\" href=\"https://app.productplan.com/integrations\">Integrations</a>\n";
echo "                </li>\n";
echo "                <li><a id=\"sign_out\" rel=\"nofollow\" data-method=\"delete\" href=\"https://app.productplan.com/users/sign_out\">Sign Out</a>\n";
echo "                </li>\n";
echo "            </ul>\n";
echo "            </a>\n";
echo "            </li>\n";
echo "            <li style='visibility:hidden;'>\n";
echo "                <a class='fullscreen-button show navbar-link' id='go-fullscreen'>\n";
echo "                    <i class='fa fa-arrows-alt' title='Start Presenter View'></i>\n";
echo "                </a>\n";
echo "            </li>\n";
echo "           </ul>\n";
echo "        </div>\n";
echo "    </nav>\n";
echo "\n";
echo "    <div id='page-content'>\n";
echo "        <div class='container-fluid'>\n";
echo "\n";
echo "            <script src=\"https://assets0.productplan.com/assets/vendor-86d82988b4ca220cbc9fea50ba377344cd53db888b25048be3d858d08d4d2c05.js\"></script>\n";
echo "            <script src=\"https://assets0.productplan.com/assets/main-a69d1d54c371ed1ac43502f293444c0e20ffce6daeca6c46c231181226d315d9.js\"></script>\n";
echo "            <div id='user-settings-content'>\n";
echo "                <!------ <div id='sections-holder'>\n";
echo "                    <div class='settings-title'>\n";
echo "                        <h1>Your Settings</h1>\n";
echo "                    </div>\n";
echo "                    <ul class='nav nav-tabs' id='settings-navigation'>\n";
echo "                        <li class='settings_tab active' id='profile'>\n";
echo "                            <i class='fa fa-user'></i>\n";
echo "                            <a href=\"/user_settings/profile\">New Item</a>\n";
echo "                        </li>\n";
echo "                        <li class='settings_tab' id='notifications'>\n";
echo "                            <i class='fa fa-bell fa-1'></i>\n";
echo "                            <a href=\"/user_settings/notifications\">Notifications</a>\n";
echo "                        </li>\n";
echo "                    </ul>\n";
echo "                </div>\n";
echo "                 -------->\n";
echo "                <div id='section-content-holder'>\n";
echo "                    <div class='flash-wrapper'>\n";
echo "\n";
echo "\n";
echo "                    </div>\n";
echo "                    <h2 class='section-title'>New Item</h2>\n";
echo "                    <div class='section-content'>\n";
echo "                        <div class='user-profile-form'>\n";
echo "                            <form class=\"simple_form form-horizontal center-block\" ";
echo "novalidate=\"novalidate\" id=\"edit_user_68339\" action=\"/apps/pcreate.php\" accept-charset=\"UTF-8\" method=\"post\">\n";
echo "                                <input name=\"utf8\" type=\"hidden\" value=\"&#x2713;\" />\n";
echo "                                <input type=\"hidden\" name=\"_method\" value=\"put\" />\n";
echo "                                <input type=\"hidden\" name=\"authenticity_token\" value=\"" . getFormKey(37645) . "\" />\n";
echo "                                <div class=\"form-group horizontal string required user_name\">\n";
echo "                                    <label class=\"string required control-label\" for=\"user_name\">Title <i class=\"required-dot\">*</i>\n";
echo "                                    </label>\n";
echo "                                    <div class=\"pp-input-wrapper\">\n";
echo "                                        <input class=\"string required form-control\" autofocus=\"autofocus\" type=\"text\" value=\"\" name=\"title\" id=\"title\" />\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                                <div class=\"form-group horizontal string required user_company_name\">\n";
echo "                                    <label class=\"string required control-label\" for=\"user_company_name\">Owner <i class=\"required-dot\">*</i>\n";
echo "                                    </label>\n";
echo "                                    <div class=\"pp-input-wrapper\">\n";
echo "                                        <input class=\"string required form-control\" type=\"text\" value=\"\" name=\"owner\" id=\"owner\" />\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                                <div class=\"form-group horizontal string optional user_phone_number\">\n";
echo "                                    <label class=\"string optional control-label\" for=\"user_phone_number\">Description </label>\n";
echo "                                    <div class=\"pp-input-wrapper\">\n";
echo "                                        <textarea class=\"string optional form-control\"  name=\"desc\" id=\"desc\" >\n";
echo "                                        </textarea>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                                <div class='form-group'>\n";
echo "                                    <div class='pp-input-aligned-buttons'>\n";
echo "                                        <input type=\"submit\" name=\"commit\" value=\"Create\" id=\"submit_btn\" class=\"btn btn-primary pull-left\" data-disable-with=\"Saving...\" />\n";
echo "                                        <a class=\"form-cancel pull-left btn btn-default\" id=\"cancel\" href=\"/apps/pp.php\">Cancel</a>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </form>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "\n";
echo "            <div class='panel panel-default' id='ajax-loader-modal'>\n";
echo "                <i class='fa fa-spinner fa-spin'></i> Updating\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <nav class='navbar navbar-fixed-bottom footer'>\n";
echo "        <div class='container-fluid'>\n";
echo "            <div class='help'>\n";
echo "               <a href='http://www.productplan.com/help' id='support' target='_blank'>\n";
echo "Help\n";
echo "</a>\n";
echo "                <span>\n";
echo "|\n";
echo "</span>\n";
echo "                <a class='intercom-link' href=''>\n";
echo "Contact Us\n";
echo "</a>\n";
echo "            </div>\n";
echo "            <div class='footer-icon'>\n";
echo "                Powered by\n";
echo "                <a href='http://productplan.com'><img src=\"https://assets0.productplan.com/assets/footer_logo-df856addd91d6c2a00d6ca63cc938882c5ca98252431a0233bd69668b1a4dbbf.png\" alt=\"Footer logo\" />\n";
echo "                </a>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </nav>\n";
echo "\n";
echo "    <!--[if lt IE 9]> <script src=\"//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js\" type=\"text/javascript\"></script> <![endif]-->\n";
echo "\n";
echo "</body>\n";
echo "\n";
echo "</html>\n";

?>
